[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hyper = { version = "0.14", features = ["http1", "http2", "server", "tcp"] }
tokio = { version = "1.21", features = ["macros", "rt-multi-thread", "signal"] }
tower = { version = "0.4", default-features = false, features = ["make"] }
tower-http = { version = "0.3", features = ["fs"] }
xshell = "0.1"
